// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/hubspot-commerce-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.HubspotCommerceSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.HubspotCommerceSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.HubspotCommerceSDK, name string) (sdk.HubspotCommerceEntity, error) {
	switch strings.ToLower(name) {
	case "advanced":
		return client.Advanced(nil), nil
	case "basic":
		return client.Basic(nil), nil
	case "batch":
		return client.Batch(nil), nil
	case "contract":
		return client.Contract(nil), nil
	case "contracts_contract":
		return client.ContractsContract(nil), nil
	case "contracts_contract_change":
		return client.ContractsContractChange(nil), nil
	case "contracts_contract_change_preview":
		return client.ContractsContractChangePreview(nil), nil
	case "contracts_contract_change_summary":
		return client.ContractsContractChangeSummary(nil), nil
	case "contracts_quote":
		return client.ContractsQuote(nil), nil
	case "item":
		return client.Item(nil), nil
	case "payment_link":
		return client.PaymentLink(nil), nil
	case "payment_methods_commerce_payment_method_settings_public":
		return client.PaymentMethodsCommercePaymentMethodSettingsPublic(nil), nil
	case "payments_action_response_with_single_result_simple_public_object":
		return client.PaymentsActionResponseWithSingleResultSimplePublicObject(nil), nil
	case "payments_create_manual_payment_public":
		return client.PaymentsCreateManualPaymentPublic(nil), nil
	case "payments_settings_get_billing_settings_public":
		return client.PaymentsSettingsGetBillingSettingsPublic(nil), nil
	case "payments_settings_get_checkout_fees_public":
		return client.PaymentsSettingsGetCheckoutFeesPublic(nil), nil
	case "payments_settings_get_policy_settings_public":
		return client.PaymentsSettingsGetPolicySettingsPublic(nil), nil
	case "payments_settings_get_shipping_settings_public":
		return client.PaymentsSettingsGetShippingSettingsPublic(nil), nil
	case "paymentsaccounts_payment_account_view":
		return client.PaymentsaccountsPaymentAccountView(nil), nil
	case "price_book":
		return client.PriceBook(nil), nil
	case "price_books_batch_response_price_book_item":
		return client.PriceBooksBatchResponsePriceBookItem(nil), nil
	case "price_books_collection_response_price_book_item_response_forward":
		return client.PriceBooksCollectionResponsePriceBookItemResponseForward(nil), nil
	case "price_books_price_book":
		return client.PriceBooksPriceBook(nil), nil
	case "price_books_price_book_item":
		return client.PriceBooksPriceBookItem(nil), nil
	case "price_books_price_book_validate":
		return client.PriceBooksPriceBookValidate(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
