<?php
declare(strict_types=1);

// HubspotCommerce SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HubspotCommerceUtility::setRegistrar(function (HubspotCommerceUtility $u): void {
    $u->clean = [HubspotCommerceClean::class, 'call'];
    $u->done = [HubspotCommerceDone::class, 'call'];
    $u->make_error = [HubspotCommerceMakeError::class, 'call'];
    $u->feature_add = [HubspotCommerceFeatureAdd::class, 'call'];
    $u->feature_hook = [HubspotCommerceFeatureHook::class, 'call'];
    $u->feature_init = [HubspotCommerceFeatureInit::class, 'call'];
    $u->fetcher = [HubspotCommerceFetcher::class, 'call'];
    $u->make_fetch_def = [HubspotCommerceMakeFetchDef::class, 'call'];
    $u->make_context = [HubspotCommerceMakeContext::class, 'call'];
    $u->make_options = [HubspotCommerceMakeOptions::class, 'call'];
    $u->make_request = [HubspotCommerceMakeRequest::class, 'call'];
    $u->make_response = [HubspotCommerceMakeResponse::class, 'call'];
    $u->make_result = [HubspotCommerceMakeResult::class, 'call'];
    $u->make_point = [HubspotCommerceMakePoint::class, 'call'];
    $u->make_spec = [HubspotCommerceMakeSpec::class, 'call'];
    $u->make_url = [HubspotCommerceMakeUrl::class, 'call'];
    $u->param = [HubspotCommerceParam::class, 'call'];
    $u->prepare_auth = [HubspotCommercePrepareAuth::class, 'call'];
    $u->prepare_body = [HubspotCommercePrepareBody::class, 'call'];
    $u->prepare_headers = [HubspotCommercePrepareHeaders::class, 'call'];
    $u->prepare_method = [HubspotCommercePrepareMethod::class, 'call'];
    $u->prepare_params = [HubspotCommercePrepareParams::class, 'call'];
    $u->prepare_path = [HubspotCommercePreparePath::class, 'call'];
    $u->prepare_query = [HubspotCommercePrepareQuery::class, 'call'];
    $u->graphql_body = [HubspotCommerceGraphql::class, 'body'];
    $u->graphql_errors = [HubspotCommerceGraphql::class, 'errors'];
    $u->result_basic = [HubspotCommerceResultBasic::class, 'call'];
    $u->result_body = [HubspotCommerceResultBody::class, 'call'];
    $u->result_headers = [HubspotCommerceResultHeaders::class, 'call'];
    $u->transform_request = [HubspotCommerceTransformRequest::class, 'call'];
    $u->transform_response = [HubspotCommerceTransformResponse::class, 'call'];
});
